name: push code server

on: 
    push:
        branches: ["main"]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Executing remote ssh commands using ssh key
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                     cd /home/azureuser/landing_page
                     git pull
                     docker build . -t img-html
                     docker run -d -p 3001:80 --name cons-html img-html
                     docker images -f "dangling=true" -q | xargs docker rmi
